
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class Principal3 extends javax.swing.JFrame {

    /**
     * Creates new form Principal3
     */
    public Principal3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSalarioDelTrabajador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumerosDeHijos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMontoTotalAPagarAlTrabajador = new javax.swing.JTextField();
        cmbCalcular = new javax.swing.JButton();
        txtBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("BONIFICACION AL TRABAJADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel2.setText("Salario del Trabajador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtSalarioDelTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalarioDelTrabajadorKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalarioDelTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, -1));

        jLabel3.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel3.setText("Números de Hijos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtNumerosDeHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosDeHijosActionPerformed(evt);
            }
        });
        txtNumerosDeHijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerosDeHijosKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumerosDeHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 80, -1));

        jLabel4.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel4.setText("Resultado de Bonificación");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 70, -1));

        jLabel5.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel5.setText("Monto total a pagar al trabajador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(txtMontoTotalAPagarAlTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 90, -1));

        cmbCalcular.setText("CALCULAR");
        cmbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtBorrar.setText("BORRAR");
        txtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumerosDeHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosDeHijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosDeHijosActionPerformed

    private void cmbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalcularActionPerformed
        // TODO add your handling code here:
        
         String  num1, num2, res;
        double n1=1,n2=1,resultado = 0, total;
        
        
        
        if (txtSalarioDelTrabajador.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el salario del tabajador", "Error",JOptionPane.ERROR_MESSAGE);
        txtSalarioDelTrabajador.requestFocusInWindow();
        } else if (txtNumerosDeHijos.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el numero de hijos", "Error",JOptionPane.ERROR_MESSAGE);
        txtNumerosDeHijos.requestFocusInWindow();
        
        
        }else {
        
            
        
        n1= Double.parseDouble(txtSalarioDelTrabajador.getText());
        n2 =Double.parseDouble(txtNumerosDeHijos.getText());
        
        
            }
        
        resultado = n2*80000;
        res= String.valueOf(resultado);
        txtResultado.setText(res);
        
        total = resultado + n1;
        res= String.valueOf(total);
        txtMontoTotalAPagarAlTrabajador.setText(res);
        
    }//GEN-LAST:event_cmbCalcularActionPerformed

    private void txtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorrarActionPerformed
        // TODO add your handling code here:
        txtSalarioDelTrabajador.setText("");
        txtNumerosDeHijos.setText("");
        txtResultado.setText("");
        txtMontoTotalAPagarAlTrabajador.setText("");
        
        txtSalarioDelTrabajador.requestFocusInWindow();
        
    }//GEN-LAST:event_txtBorrarActionPerformed

    private void txtSalarioDelTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioDelTrabajadorKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtSalarioDelTrabajadorKeyTyped

    private void txtNumerosDeHijosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerosDeHijosKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtNumerosDeHijosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton txtBorrar;
    private javax.swing.JTextField txtMontoTotalAPagarAlTrabajador;
    private javax.swing.JTextField txtNumerosDeHijos;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSalarioDelTrabajador;
    // End of variables declaration//GEN-END:variables
}
